#pragma once
#include <cstddef>
#include <cstdint>

namespace nsc_sfx_list_generated {
inline constexpr std::size_t kCount = 160;
inline constexpr const char* kNames[kCount] = {
    "S_PL_ATK_cmn_vS_rv",
    "S_PL_ATK_cmn_vM_rv",
    "S_PL_ATK_cmbUp",
    "S_PL_ATK_cmbNeutral",
    "S_PL_ATK_cmbDown",
    "S_PL_ATK_cmb_air",
    "S_PL_ATK_throw_v0",
    "S_PL_ATK_throw_v1",
    "S_PL_ATK_throw_v2",
    "S_PL_ATK_throw_v3",
    "S_PL_etc_a",
    "S_PL_etc_b",
    "S_PL_etc_c",
    "S_PL_etc_d",
    "S_PL_etc_e",
    "S_PL_etc_f",
    "S_PL_etc_g",
    "S_PL_etc_h",
    "S_PL_etc_i",
    "S_PL_etc_j",
    "S_PL_etc_k",
    "S_PL_etc_l",
    "S_PL_etc_m",
    "S_PL_etc_n",
    "S_PL_etc_o",
    "S_PL_etc_p",
    "S_PL_ATK_ckrAtk_a_v0",
    "S_PL_ATK_ckrAtk_a_v1",
    "S_PL_ATK_ckrAtk_a_v2",
    "S_PL_ATK_ckrAtk_a_v3",
    "S_PL_ATK_ckrAtk_b_v0",
    "S_PL_ATK_ckrAtk_b_v1",
    "S_PL_ATK_ckrAtk_b_v2",
    "S_PL_ATK_ckrAtk_b_v3",
    "S_PL_ATK_ckrAtk_c_v0",
    "S_PL_ATK_ckrAtk_c_v1",
    "S_PL_ATK_ckrAtk_c_v2",
    "S_PL_ATK_ckrAtk_c_v3",
    "S_PL_ATK_ckrAtk_d_v0",
    "S_PL_ATK_ckrAtk_d_v1",
    "S_PL_ATK_ckrAtk_d_v2",
    "S_PL_ATK_ckrAtk_d_v3",
    "S_PL_ATK_ckrAtk_e_v0",
    "S_PL_ATK_ckrAtk_e_v1",
    "S_PL_ATK_ckrAtk_e_v2",
    "S_PL_ATK_ckrAtk_e_v3",
    "S_PL_ATK_ckrAtk_f_v0",
    "S_PL_ATK_ckrAtk_f_v1",
    "S_PL_ATK_ckrAtk_f_v2",
    "S_PL_ATK_ckrAtk_f_v3",
    "S_PL_ATK_ckrAtk_g_v0",
    "S_PL_ATK_ckrAtk_g_v1",
    "S_PL_ATK_ckrAtk_g_v2",
    "S_PL_ATK_ckrAtk_g_v3",
    "S_PL_ATK_ckrAtk_h_v0",
    "S_PL_ATK_ckrAtk_h_v1",
    "S_PL_ATK_ckrAtk_h_v2",
    "S_PL_ATK_ckrAtk_h_v3",
    "S_PL_ATK_ckrAtk_air_a_v0",
    "S_PL_ATK_ckrAtk_air_a_v1",
    "S_PL_ATK_ckrAtk_air_a_v2",
    "S_PL_ATK_ckrAtk_air_a_v3",
    "S_PL_ATK_ckrAtk_air_b_v0",
    "S_PL_ATK_ckrAtk_air_b_v1",
    "S_PL_ATK_ckrAtk_air_b_v2",
    "S_PL_ATK_ckrAtk_air_b_v3",
    "S_PL_ATK_ckrAtk_air_c_v0",
    "S_PL_ATK_ckrAtk_air_c_v1",
    "S_PL_ATK_ckrAtk_air_c_v2",
    "S_PL_ATK_ckrAtk_air_c_v3",
    "S_PL_ATK_ckrAtk_air_d_v0",
    "S_PL_ATK_ckrAtk_air_d_v1",
    "S_PL_ATK_ckrAtk_air_d_v2",
    "S_PL_ATK_ckrAtk_air_d_v3",
    "S_PL_ATK_ckrAtk_air_e_v0",
    "S_PL_ATK_ckrAtk_air_e_v1",
    "S_PL_ATK_ckrAtk_air_e_v2",
    "S_PL_ATK_ckrAtk_air_e_v3",
    "S_PL_ATK_ckrAtk_air_f_v0",
    "S_PL_ATK_ckrAtk_air_f_v1",
    "S_PL_ATK_ckrAtk_air_f_v2",
    "S_PL_ATK_ckrAtk_air_f_v3",
    "S_PL_ATK_ckrAtk_air_g_v0",
    "S_PL_ATK_ckrAtk_air_g_v1",
    "S_PL_ATK_ckrAtk_air_g_v2",
    "S_PL_ATK_ckrAtk_air_g_v3",
    "S_PL_ATK_ckrAtk_air_h_v0",
    "S_PL_ATK_ckrAtk_air_h_v1",
    "S_PL_ATK_ckrAtk_air_h_v2",
    "S_PL_ATK_ckrAtk_air_h_v3",
    "S_PL_ATK_dart",
    "S_PL_ATK_dart_air",
    "S_PL_ATK_ckrDart",
    "S_PL_ATK_ckrDart_air",
    "S_PL_ATK_counter_ready",
    "S_PL_ATK_guardBrk",
    "S_PL_ATK_middleDistance",
    "S_PL_ATK_throw_trgAtk",
    "S_PL_ATK_UJ_trgAtk_a",
    "S_PL_ATK_UJ_trgAtk_b",
    "S_PL_ATK_UJ_trgAtk_c",
    "S_PL_ATK_UJ_trgAtk_d",
    "S_PL_AWK_ready",
    "S_PL_AWK_start",
    "S_PL_AWK_end",
    "S_PL_AWK_reReady",
    "S_PL_AWKt_ready",
    "S_PL_AWKt_start",
    "S_PL_AWKt_end",
    "S_PL_AWKt_reReady",
    "S_PL_ckrCharge",
    "S_PL_ckrCharge_toAwk",
    "S_PL_ckrDash_back",
    "S_PL_ckrDash_front",
    "S_PL_ckrDash_charge",
    "S_PL_jump",
    "S_PL_jump_double",
    "S_PL_njaDash",
    "S_PL_njaMove_rv",
    "S_PL_ITM_atk",
    "S_PL_ITM_Characteristic",
    "S_PL_ITM_powerUp",
    "S_PL_ITM_ckrRecover",
    "S_PL_substitution_rv",
    "S_PL_substitution_dart_rv",
    "S_PL_SPT_breakGuard",
    "S_PL_SPT_chargeGuard",
    "S_PL_SPT_cmbSupport",
    "S_PL_SPT_coverFire",
    "S_PL_SPT_dashCut",
    "S_PL_SPT_entry",
    "S_PL_SPT_fallingsubstitution",
    "S_PL_SPT_leave",
    "S_PL_SPT_leave_UJt",
    "S_PL_SPT_ready",
    "S_PL_SPT_strikeBack",
    "S_PL_SPT_UJ_substitution",
    "S_PL_SPT_UJt_trgAtk",
    "S_PL_SPT_mainChange_rv",
    "S_PL_SPT_dominance",
    "S_PL_SPT_backfoot",
    "S_PL_mainChange_rv",
    "S_PL_gaugeMax",
    "S_PL_limitBreak",
    "S_PL_ATK_cmbChain_trgAtk",
    "S_PL_ATK_cmbChain",
    "S_PL_SPT_cmbChain_v0",
    "S_PL_SPT_cmbChain_v1",
    "S_PL_SPT_cmbChain_v2",
    "S_PL_SPT_cmbChain_v3",
    "S_PL_ATK_backGroundChange_rv",
    "S_PL_SPT_mainChangeAtk_rv",
    "S_PL_thanks",
    "S_PL_DMG_cmn_vS_rv",
    "S_PL_DMG_cmn_vM_rv",
    "S_PL_DMG_cmn_vL_rv",
    "S_PL_DMG_death_vS",
    "S_PL_DMG_death_vL",
    "S_PL_DMG_guardBrk",
    "S_PL_DMG_supportClash",
};

inline bool Equal(const char* a, const char* b) {
    if (!a || !b) return false;
    for (;;) {
        if (*a != *b) return false;
        if (*a == 0) return true;
        ++a; ++b;
    }
}

inline int32_t FindIndex(const char* text) {
    for (std::size_t i = 0; i < kCount; ++i) {
        if (Equal(kNames[i], text)) return static_cast<int32_t>(i);
    }
    return -1;
}

} // namespace nsc_sfx_list_generated
