#pragma once

namespace nsc {
void InstallP50AConditionCompat();
void InstallP52APreUjProbe();
void InstallP53AInputPromotionProbe();
void InstallP54ADirectJutsuProbe();
void InstallP55AStateSampler();
void InstallP56BControlLocator();
void InstallP57ACentralSetterTrace();
void InstallP58APlayActionCallerTrace();
void InstallP59AActionModeDispatchTrace();
void InstallP63AUjRouterFirstDivergenceTrace();
void InstallP64FUjSemanticBridge();
void InstallP65ASourceParityActiveUjBridge();
void InstallP66AVirtualUjSemanticBridge();
void InstallP67AActiveSelector1ConsumerBridge();
void InstallP76AForkRuntimeProbe();
void InstallP77AAcceptanceProbe();
void InstallP78ASemanticAltRouteProbe();
void InstallP79ADualSubpredicateProbe();
void InstallP80BDeepConditionTrace();
void InstallP81AOugiAwakeningPolicyBridge();
void InstallP82ADownstreamCorridorProbe();
void InstallP83ASlot1928PolicyBridge();
void InstallP84AIntentDiscriminator();
void InstallP85AF58IntentProbe();
void InstallP86ABda4Bdc8ProducerProbe();
void InstallP87AActiveProducerProbe();
void InstallP88BBootSafeUJHelperProbe();
void InstallP89APhase3ActorPredBridge();
void InstallP91AFocusedHandoffStateTrace();
void InstallP92AFocusedHandoffStateSweep();
void InstallP93AMaxUsefulTrace();
void InstallP94ASequenceControllerTrace();
void InstallP95AQueuedActionParentTrace();
void InstallP96AActionDescriptorTransitionTrace();
void InstallP88AWideUJAdmissionTrace();
void InstallP105ADualSiblingControllerTrace();
}
